server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: COMPANY-SERVICE
        uri: lb://COMPANY-SERVICE
        predicates:
          - Path=/company/**
          
      - id: GET-JOB-POST-SERVICE
        uri: lb://GET-JOB-POST-SERVICE
        predicates:
          - Path=/getpost/**
          
      - id: JOB-PUBLISH-SERVICE
        uri: lb://JOB-PUBLISH-SERVICE
        predicates:
          - Path=/job/**
          
      - id: JOB-TYPE-SERVICE
        uri: lb://JOB-TYPE-SERVICE
        predicates:
          - Path=/type/**