server:
  port: 9001
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/jobapp_companyService
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: restaurant-service